name: task_demo
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.12
  fluttertoast: ^8.0.9
  keyboard_actions: ^4.0.1
  flutter_overlay_loader: ^2.0.0
  intl: any
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  floor: ^1.2.0
  loading_indicator: ^3.0.3
  cached_network_image: ^3.2.0
  pull_to_refresh_flutter3: ^2.0.1
  overlay_support: ^2.0.1
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  json_serializable: ^6.1.5
  retrofit_generator:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.4
  floor_generator: ^1.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lang/


